version: "3.0"
services:
  backend:
    build: ./Backend
    volumes:
      - /usr/JukeBox_backup:/usr/JukeBox_backup
    ports:
      - "5000:5000"
  
  frontend:
    build: ./Frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend